"$schema" = "https://starship.rs/config-schema.json"

[git_status]
ahead = "^"
behind = "⌄"
deleted = "x"
diverged = "Y"
renamed = ">"

[directory]
fish_style_pwd_dir_length = 1
truncate_to_repo = false
truncation_length = 2
