require("settings.indentation")
require("settings.navigation")
require("settings.options")
require("settings.sessions")
require("settings.statusline")
require("settings.terminal")
require("settings.utils")
