return {
	{
		"https://github.com/mason-org/mason.nvim",
		cmd = { "Mason", "MasonUpdate" },
		opts = { PATH = "append" },
	},
	{
		"https://github.com/mason-org/mason-lspconfig.nvim",
		lazy = false,
		opts = {},
	},
	{
		"https://github.com/WhoIsSethDaniel/mason-tool-installer.nvim",
		cmd = { "MasonToolsUpdate" },
		opts = {
			ensure_installed = {
				"basedpyright",
				"bashls",
				"biome",
				"checkmake",
				"clangd",
				"cmake",
				"commitlint",
				"eslint",
				"fourmolu",
				"golangci-lint",
				"golangci_lint_ls",
				"gopls",
				"jsonls",
				"just-lsp",
				"lua_ls",
				"marksman",
				"oxlint",
				"pkl-lsp",
				"prettierd",
				"ruff",
				"shellcheck",
				"shfmt",
				"stylua",
				"taplo",
				"vimls",
				"vtsls",
				"yamlfmt",
				"yamlls",
			},
		},
	},
}
