require("my.options")
require("my.lsp")

require("my.autocommands")
require("my.diagnostics")
require("my.filetypes")
require("my.folding")
require("my.highlights")
require("my.indentation")
require("my.keymaps")
require("my.sessions")
require("my.statusline")
require("my.terminal")
require("my.user_commands")
