#!/usr/bin/env bash

# Adapted from:
# https://mjones.network/storing-dotfiles-in-a-git-repo
# https://harfangk.github.io/2016/09/18/manage-dotfiles-with-a-git-bare-repository.html

git clone --bare git@github.com:heygarrett/dotfiles.git $HOME/.dotfiles

# define config alias locally since the dotfiles
# aren't installed on the system yet
function dotfiles {
   git --git-dir=$HOME/.dotfiles/ --work-tree=$HOME $@
}

# checkout dotfiles from repo
dotfiles checkout
dotfiles config status.showUntrackedFiles no
