require("my.settings.options")
require("my.settings.lsp")

require("my.settings.autocommands")
require("my.settings.diagnostics")
require("my.settings.filetypes")
require("my.settings.folding")
require("my.settings.indentation")
require("my.settings.keymaps")
require("my.settings.sessions")
require("my.settings.statusline")
require("my.settings.terminal")
require("my.settings.user_commands")
